checkout/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('payments.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),
    

]+ static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)

payments/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields.related import OneToOneField
from django.urls import reverse

# Create your models here.

class Admin_user(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    joined_date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return str(self.user)


class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200 ,null= True, blank=True )
    joined_date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return str(self.user)


# CATERGORY STORE KARANA DATABASE EKA
class Catergory(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("admin_product")


# PRODUCT STORE KARANA DATABASE EKA
class Product(models.Model):
    catergory = models.ForeignKey(Catergory,on_delete=models.CASCADE)
    product_name = models.CharField(max_length=500)
    slug = models.SlugField(unique=True)
    image =models.ImageField(upload_to= 'products')
    market_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    discriptions = models.TextField()
    worenty = models.CharField(max_length=200,null=True,blank=True)
    return_policy =models.CharField(max_length=200,null=True,blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.product_name

class Pimage(models.Model):
    proimage=models.ForeignKey(Product,on_delete=models.CASCADE)
    ima =models.ImageField(upload_to='product/images')

    def __str__(self):
        return self.proimage
    
    

#ALUTHIN CART EKAK CREATE KALAMA EKA STORE WENA DATABASE EKA
class Cart(models.Model):
    customer = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True)
    total = models.PositiveIntegerField(default=0)
    creat_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Cart:' + str(self.id)


#CART EKATA PRODUCT ADD KALAMA EKE DATA STORE WENA DARTABASE EKA
class CartProduct(models.Model):
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return 'Cart:' + str(self.cart.id) + 'Cart product:' + str(self.id)


# ORDER EKA GATHTHAMA STORE KARANA DETABASE EKA
Order_Status={
    ('order received','order received '),
    ('order processing','order processing '),
    ('order is on the way','order is on the way '),
    ('order completed','order completed '),
    ('order cancled','order canceled '),

}
payment_choice={
    ('Cash on Delivery','Cash on Delivery '),
    ('Card Payment','Card Payment '),

}
class Order(models.Model):
    cart = OneToOneField(Cart,on_delete=models.CASCADE)
    order_by = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    town = models.CharField(max_length=200)
    mobile = models.CharField(max_length=200)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=200,choices=Order_Status)
    created_at = models.DateTimeField(auto_now_add=True)
    pyment_method = models.CharField(max_length=30,choices=payment_choice,default='Cash on Delivery')

    def __str__(self):
        return 'Order:'+ str(self.id) 
    
class slider(models.Model):
    image =models.ImageField(upload_to= 'products')

    

    def get_absolute_url(self):
        return reverse("slider")
    
    
    

templates/add_to_cart.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div class="row">
    <div class="col-md-6">
        <img src="{% static 'istockphoto-1263966097-612x612.jpg' %}" alt="" width="100%" height="100%">

    </div>
    <div class="col-md-6">
        <h3 style="color:chocolate;font-family:Cambria;" class="text-center fw-bold">Product added to Cart is successful.</br>Please check your cart.....</h3>
    </div>
</div>



{% endblock body %}

templates/allcatergory.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
<div class="container">
    <h3 class="text-center mt-3 fw-bold shadow mb-3">All Catergory Page</h3>
    {% for cat in allcatergory %}
        <h4 class="fw-bold">{{cat.title}}</h4>
        <hr class="mt-3">
    <div class="row ">
        {% for pro in cat.product_set.all %}
        <div class="col-md-4 mt-3">
            <div class="card shadow" style="width: 18rem;" >
				<img src="{{pro.image.url}}" class="card-img-top" alt="..."width="200" height="200">
				<div class="card-body">
				  <h5 class="card-title"><a class="lin text-decoration-none" href="{% url 'product_details' pro.slug %}">{{pro.product_name}}</a></h5>
				  <strike class="badge bg-primary text-warp">Rs.{{pro.market_price}}.00</strike>
                  <h6 class="fw-bold text-danger text-center">Rs.{{pro.selling_price}}.00</h6>
                  <a href="{% url 'add_to_cart' pro.id %}" class="btn btn-primary">Add to cart</a>
				  
				</div>
			</div>
        </div>
        {% endfor %}
    </div>


    {% endfor %}


</div>


{% endblock body %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
     <!-- slick slider CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.min.css" integrity="sha512-17EgCFERpgZKcm0j0fEq1YCJuyAWdz9KUtv1EjVuaOz8pDnh/0nZxmU6BBXwaaxqoi9PQXnRWqlcDB027hgv9A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css" integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
     <!-- style CSS -->
    <link rel="stylesheet" href={% static "style.css" %}> 
     <!-- font awesome CSS -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    {% block title %}{% endblock title %}
  </head>
<body id ="bg" style="background-image: url('{% static '135-1356215_background-wallpaper-and-blue-image-sky-blue-background.jpg' %}');">

    
  <nav class="navbar navbar-expand-lg bg-opacity-50  navbar-light bg-light py-3">
    <div class="container">
      <a class="navbar-brand fw-bold "><img class="nav-img" src="{% static 'fashion-store-boutique-isolated-icon-female-clothes-shop-sketch-vector-dress-belt-womens-wear-hand-drawn-emblem-logo-165525576.jpg' %}" alt=""></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span> <i id ="bar" class="fas fa-bars"></i></span>
      </button>
      <div class= "collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link fw-bold" aria-current="page" href="{% url 'home' %}"><i class="fas fa-store"></i></a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link fw-bold" href="{% url 'allcatergory' %}"><i class="fas fa-globe"> Catergory</i></a>
          </li>
          
          
           {% if request.user.is_superuser %}
           <h6>Wellcome: {{request.user.username}}</h6>
          <li class="nav-item">
            <a class="nav-link fw-bold" href="{% url 'addproduct' %}">Add Product</a>
          </li>
          <li class="nav-item">
            <a class="nav-link fw-bold" href="{% url 'slider' %}">Add Image Slider</a>
          </li>
          <li class="nav-item">
            <a class="nav-link fw-bold" href="{% url 'addcatergory' %}">Add Catergory</a>
          </li>
          {% endif %}
        
          <li class="nav-item">
            <a class="nav-link fw-bold" href="{% url 'my_cart' %}">
             <i class="fas fa-shopping-bag"></i>
            </a>
            
          </li>
          <li class="nav-item" >
          <form class="d-flex"action ="{% url 'search'%}" method="GET">
          <input class="form-control me-2" style="opacity: 50%; font-family: 'Courier New', Courier, monospace; font-size: small; border-radius: 25%; border-width: 2px;" type="search" placeholder="Search" aria-label="Search" name ='keyword' Required>
          <button class="btn" style="border-radius: 50%; padding: 0 30px;" type='submit'><i class="fas fa-search" ></i></button>
          </form>
          </li>
           <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle fw-bold" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            
            <i class="fas fa-user-circle"></i>
            </a>
            
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
             

              {% if request.user.customer or request.user.is_authenticated %}
                  
                  <h6 class= "fw-bold">Welcome: {{request.user.username}}</h6>
              <li><a class="dropdown-item" href="{% url 'custermor_logout' %}"><i class="fas fa-power-off"></i>Logout</a></li>
              {% else %}
              <li><a class="dropdown-item" href="{% url 'custermor_login' %}"><i class="fas fa-user"></i>  Login</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'custermor_register' %}">
              <i class="fas fa-user-plus"></i>  Register</a></li>
              {% endif %}
            </ul>
          </li>
        </ul>
       
       
      </div>
    </div>
  </nav>
  
  
   {% block body %}{% endblock body %}
  
     
  
    
   <footer class="footer mt-5 py-5">
    <div class="row container mx-auto pt-5">
      <div class="footer-1 col-lg-3 col-md-6 col-12">
        <img class="mt-3" style= "border-radius: 50%;" src="{% static 'fashion-store-boutique-isolated-icon-female-clothes-shop-sketch-vector-dress-belt-womens-wear-hand-drawn-emblem-logo-165525576.jpg' %}" alt="">
        <h5>This is who we are</h5>
        <p class="pt-3">One of the leading eCommerce store in Sri Lanka.
          yor stay at home and intouch with us. We will send trending
        fasions to you  </p>
      </div>
      <div class="footer-2 col-lg-3 col-md-6 col-12">
        <h5 class="mt-2">Links</h5>
        <ul class="text-uppercase list-unstyled">
          <li><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'allcatergory' %}">Catergory</a></li>
          <li><a href="{% url 'my_cart' %}">Cart</a></li>
          <li><a href="{% url 'custermor_login' %}">Login</a></li>
          <li><a href="{% url 'custermor_register' %}">Register</a></li>
        </ul>
      </div>
      <div class="footer-2 col-lg-3 col-md-6 col-12">
        <h5 class="mt-2">Contact us</h5>
        <h6 class="text-uppercase">address</h6>
        <p>No. 473/37f, Samupakara Mv, Palanwathta, Pannipitiya.</p>
        <h6 class="text-uppercase">phone</h6>
        <p>078 3813599</p>
        <h6 class="text-uppercase">email</h6>
        <p>isuruhewawasam@gmail.com</p>
      </div>
    </div>
    <div class="copyright mt-5">
      <div class="row container mx-auto">
        <div class="col-lg-3 col-md-6 col-12">
          <i class="fab fa-cc-paypal"></i>
          <i class="fab fa-cc-visa"></i>
          <i class="fab fa-cc-mastercard"></i>
        </div>
        <div class="col-lg-4 col-md-6 col-12 text-nowrap">
         <p> eCommerce ~ 2021. All Rights Reserved.</p>
        </div>
        <div class="col-lg-3 col-md-6 col-12">
          <i class="fab fa-facebook-f"></i>
          <i class="fab fa-twitter"></i>
          <i class="fab fa-linkedin-in"></i>
          <i class="fab fa-instagram"></i>
        </div>

      </div>
      
    </div>
  </footer> 
  
      <!-- Optional JavaScript; choose one of the two! -->
  
      <!-- Option 1: Bootstrap Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  
      <!-- Option 2: Separate Popper and Bootstrap JS -->
      <!--
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
      -->
       <!-- Slick slider JS -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js" integrity="sha512-HGOnQO9+SP1V92SrtZfjqxxtLmVzqZpjFFekvzZVWoiASSQgSr4cw9Kqd2+l8Llp4Gm0G8GIFJ4ddwZilcdb8A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
      <script type="text/javascript">
   ///slick slider add karana thana     
  $('.slider').slick({
    centerMode: true,
    infinite: true,
    centerPadding: '10px',
    slidesToShow: 1,
    autoplay: true,
    autoplaySpeed: 5000,
    responsive: [
      {
        breakpoint: 480,
        settings: {
          arrows: true,
          centerMode: true,
          centerPadding: '40px',
          slidesToShow: 1
        }
      },
      {
        breakpoint: 480,
        settings: {
          arrows: true,
          centerMode: true,
          centerPadding: '40px',
          slidesToShow: 1
        }
      }
    ]
  });
  
  $('.product-center').slick({
    centerMode: true,
    centerPadding: '60px',
    slidesToShow: 3,
    responsive: [
      {
        breakpoint: 768,
        settings: {
          arrows: false,
          centerMode: true,
          centerPadding: '40px',
          slidesToShow: 1
        }
      },
      {
        breakpoint: 480,
        settings: {
          arrows: false,
          centerMode: true,
          centerPadding: '40px',
          slidesToShow: 1
        }
      }
    ]
  });

  $('.small-img-col').slick({
  
  infinite: true,
  speed: 500,
  fade: true,
  cssEase: 'linear'
});

 
      
      </script>
    

  
  </body>
</html>

templates/card_payment.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    
    <script src='main.js'></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.min.css" integrity="sha512-17EgCFERpgZKcm0j0fEq1YCJuyAWdz9KUtv1EjVuaOz8pDnh/0nZxmU6BBXwaaxqoi9PQXnRWqlcDB027hgv9A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css" integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <script type="text/javascript" src="https://www.payhere.lk/lib/payhere.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <button type="submit" id="payhere-payment" >PayHere Pay</button>

<h3>Amount : {{order.total}}</h3>
<form action="" method="post">
    {% csrf_token %}
    
    <input  id ="demo" type="text" name="success">
    <button id="btn" type="submit"></button>
    
</form>
<script>


    // Called when user completed the payment. It can be a successful payment or failure
    payhere.onCompleted = function onCompleted(orderId) {
   
   
   
        console.log("Payment completed. OrderID:" + orderId);
        document.getElementById("demo").innerHTML ='payment successfull'
        alert("Payment Completed");
        //Note: validate the payment and show success or failure page to the customer
    };

    // Called when user closes the payment without completing
    payhere.onDismissed = function onDismissed() {
        //Note: Prompt user to pay again or show an error page
        console.log("Payment dismissed");
        alert("Payment Cancel");
    };

    // Called when error happens when initializing payment such as invalid parameters
    payhere.onError = function onError(error) {
        // Note: show an error page
        console.log("Error:"  + error);
        alert("Error:"  + error);
        
    };

    // Put the payment variables here
    var payment = {
        "sandbox": true,
        "merchant_id": "1218640",    // Replace your Merchant ID
        "return_url": "localhost:8000/",     // Important
        "cancel_url": "localhost:8000/",     // Important
        "notify_url": "http://sample.com/notify",
        "order_id": "{{order.id}}",
        "items": "Door bell wireles",
        "amount": "{{order.total}}",
        "currency": "LKR",
        "first_name": "{{order.order_by}}",
        "last_name": "{{order.last_name}}",
        "email": "{{order.email}}",
        "phone": "{{order.mobile}}",
        "address": "No.1, Galle Road",
        "city": "Colombo",
        "country": "Sri Lanka",
        "delivery_address": "No. 46, Galle road, Kalutara South",
        "delivery_city": "Kalutara",
        "delivery_country": "Sri Lanka",
        "custom_1": "",
        "custom_2": ""
    };

    // Show the payhere.js popup, when "PayHere Pay" is clicked
    document.getElementById('payhere-payment').onclick = function (e) {
        payhere.startPayment(payment);
    };
</script>

</body>
</html>

templates/cart.html
{% extends 'base.html' %}


{% block body %}

<div class="container">
    <div class="row mt-5">
        <div class="col-lg-12 col-md-8">
        <a href="{% url 'home'%}"><button class="btn btn-outline-danger mt-3">Back</button></a>
            <h4 class ='text-center'>Items in my cart</h4><hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                        <td>
                            <a href="{% url 'managecart' cp.id %}?action=inc" class="btn btn-primary"> + </a>
                            <a href="{% url 'managecart' cp.id %}?action=dcr" class="btn btn-warning"> - </a>
                            <a href="{% url 'managecart' cp.id %}?action=rmv" class="btn btn-danger"> x </a>
                        </td>
                    </tr>
                      
                    {% endfor %}
                     <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                        {% if cart.cartproduct_set.all %}
                        <th><a class="btn btn-danger" href="{% url 'emptycart' %}">Empty Cart</a></th>
                        {% endif %}
                    
                    </tr>
                    {% if cart.cartproduct_set.all %}
                    <tr>
                        <th><a class="btn btn-info" href="{% url 'place_order' %}"> Checkout </a></th>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>



{% endblock body %}

templates/customer_login.html
{% extends 'base.html' %}


{% block body %}


<div class="container ">

    <h3 class="text-center text-decoration-underline mt-3 fw-bold" >Login Form</h3>
    <hr class="mt-5">
    <div class="row">
        <div class="col-md-6">
            <form action="" method="post">
                {% csrf_token %}
                {{form.as_p}}
                
                <button class="btn-outline-info btn-lg mt-3" type="submit" >
                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-save2" viewBox="0 0 16 16">
  <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
</svg>Login
                </button>
                {% if error %}

                    <li style="color: red;">
                        {{error}}
                    </li>
                {% endif %}
            </form>
            <hr>
            <a href="{% url 'reset_password' %}">Forget your Password
            </a>
        </div>
        <div class="col-md-6">
            <h6 class="ml-5" style= " color: coral; font-family: 'Courier New', Courier, monospace; font-size: x-large;font-weight: bold;">Login With</h6>
            <hr class="mx-start">
            <button class="btn btn-light mb-2  ml-5 mr-2 " >
                <a href="{% url 'social:begin' 'google-oauth2' %}"> <i class="fab fa-google"></i>
                </a>
            </button>
            <button class="btn btn-light mb-2">
                <a href="{% url 'social:begin' 'facebook' %}"> <i class="fab fa-facebook-f"></i>
                </a>
            </button>
        </div>  
    </div>
</div>
{% endblock %}

templates/details.html
{% extends 'base.html' %}


<section class="my-5 pt-5">
    {% block body %}
    <h3 class="text-center fw-bolder mt-3 g-2">{{product_details.product_name}}</h3>
    <hr class="mt-4">

    <div class="container">
        <div class="row mt-5">
            <div class="col-lg-5 col-md-12 col-12">
                <img src="{{product_details.image.url}}" class="img-fluid pb-1" alt="..." id="maim-img">
                <div class="small-img-group" style="display: inline; justify-content: space-between;">
                    <div class="small-img-col" style="flex-basis: 24%; cursor: pointer;">
                        {% for pi in product_details.pimage_set.all %}
                        
                        <img src="{{pi.ima.url}}" alt="" class="img-small" width="100px" height="300px">
                        
                        {% endfor%}
                    </div>

                </div>
                
            </div>
            
            <div class="col-lg-6 col-md-12 col-12">
                <h4 class="fw-bolder">Product Name: {{product_details.product_name}}</h4>
                <strike class="badge bg-danger text-warp">Market Price: Rs.{{product_details.market_price}}.00</strike> 
                <h5>Selling Price: Rs.{{product_details.selling_price}}.00</h5>
                <a href="{% url 'add_to_cart' product_details.id %}" class="btn btn-primary">Add to cart</a>
                <hr>
                <p class="fw-bolder"> Discriptions:{{product_details.discriptions}}</p>
                <p class="text-info">Worrenty:{{product_details.worenty}}</p>
                <p class="text-info">Return Policy:{{product_details.return_policy}}</p>
                <p class="text-success">(Viewed: {{product_details.view_count}} times)</p>

            </div>

    
    
           
        </div>
    </div>
    
    
{% endblock body %}


</section>

templates/placeorder.html
{% extends 'base.html'%}


{% block body %}

<div class="container">
    <div class="row">
        <h4 class ='text-center'>Place Order</h4><hr>
        <div class="col-md-6">
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        
                    </tr>
                </thead>
            <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                       
                    </tr>
                      
                    {% endfor %}
                     <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                        
                    
                    </tr>
                   
            </tbody>
            </table>
        </div>
        <div class="col-md-6">
        <a href="{% url 'my_cart'%}"><button class="btn btn-outline-danger mt-3">Back</button></a>
            <h2 class="fw-bold"> Checkout Form</h2>
            <form action="" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-info">Place order</button>
                
            </form>
        </div>
    </div>
</div>




{% endblock body %}